### ISSUE TITLE
0 sentence 

### ISSUE THREAD

**Issue by zz0807** [hantek/distance-parser#1]
I do as the readme and get the following info
Generating ../data/ctb_liusplit\train.txt
795 files...
100.00%
0 sentences.

Generating ../data/ctb_liusplit\dev.txt
25 files...
100.00%
0 sentences.

Generating ../data/ctb_liusplit\test.txt
30 files...
100.00%
0 sentences.

And don't know why I get 0 sentences

**Comment by zz0807** [comment]
I am using windows. This issue have been solved by setting encoding ="utf-8"      
```
  with open(join(ctb_root, f), 'r', encoding="utf-8") as src, \
             open(join(out_root, f.split('.')[0] + '.fid'), 'w', encoding="utf-8") as out:
```

**Comment by hantek** [comment]
Great to know that you have solved it and I appreciate it that you posted your solution on the site! I am going to close this issue since it is solved already.
